# Generated by Django 5.0.2 on 2024-02-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='empty_avatar.jpg', null=True, upload_to='profile'),
        ),
    ]
