# Generated by Django 5.0.2 on 2024-03-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='sugar_level',
            field=models.FloatField(),
        ),
    ]
